### ISSUE TITLE
analyze_results.py fails when run the input is the run directory

### ISSUE THREAD

**Issue by baba-hashimoto** [luancarvalhomartins/PyAutoFEP#12]
(PyAutoFEP) tbaba@YW113:/work113/test/PyAutoFEP/docs/tutorial01_fin$ python ../../analyze_results.py --input tutorial.tgz --units kcal --output_uncompress_directory tutorial --center_molecule=FXR_12

Bad key "text.kerning_factor" on line 4 in
/home1/test/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
All available analysis will be run
Traceback (most recent call last):
  File "../../analyze_results.py", line 1478, in <module>
    verbosity=arguments.verbose)
  File "../../analyze_results.py", line 1139, in collect_from_xvg
    with open(os.path.join(xvg_directory, unk_file), 'rb') as fh:
NotADirectoryError: [Errno 20] Not a directory: 'tutorial/FXR_12-FXR_74/runall_FXR_12-FXR_74_water.sh/md/rerun/unk_matrix.pkl'

After all the calculations were completed, I ran the above command and got an error. 
 The cause is the path of the file.　It should be tutorial/FXR_12-FXR_74/water/md/rerun/unk_matrix.pkl, but it is tutorial/FXR_12-FXR_74/runall_FXR_12-FXR_74_water.sh/md/rerun/unk_ matrix.pkl. I was not sure where to modify to change the path name, so I would appreciate your advice.

**Comment by baba-hashimoto** [comment]
Now that the REST2 calculations are complete, we ran the analysis and got the following results.

(PyAutoFEP) tmp@YW113:/work113/tmp/PyAutoFEP/docs/tutorial01_plumed$ python ../../analyze_results.py --input tutorial.tgz --units kcal  --center_molecule=FXR_12

Bad key "text.kerning_factor" on line 4 in
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
All available analysis will be run
==================================================
         Perturbation           protein    water
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/tight_layout.py:228: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/tight_layout.py:228: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/tight_layout.py:228: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/tight_layout.py:228: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/tight_layout.py:228: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/tight_layout.py:228: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/tight_layout.py:228: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/tight_layout.py:228: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/tight_layout.py:228: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/tight_layout.py:228: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/work113/tmp/PyAutoFEP/os_util.py", line 359, in wrapper_fn
    return fn(*args, **kwargs)
  File "../../analyze_results.py", line 934, in analyze_perturbation
    output_file=os.path.join(output_directory, 'hrex_coord_hamiltonians.svg'))
  File "../../analyze_results.py", line 788, in plot_stacked_bars
    ticks=numpy.arange(0, n_rep + 1) + 0.5)
  File "/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2320, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)
  File "/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/figure.py", line 2098, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **cb_kw)
  File "/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/colorbar.py", line 1399, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/colorbar.py", line 920, in __init__
    mappable.autoscale_None()
  File "/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/site-packages/matplotlib/cm.py", line 362, in autoscale_None
    raise TypeError('You must first set_array for mappable')
TypeError: You must first set_array for mappable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../analyze_results.py", line 1648, in <module>
    kwargs_iter=arguments_data_holder.values())
  File "/work113/tmp/PyAutoFEP/os_util.py", line 380, in starmap_unpack
    return pool.starmap(wrapper_fn, list(assembled_args))
  File "/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home1/tmp/ubuntu20/anaconda3/envs/PyAutoFEP/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: You must first set_array for mappable

I am attaching the input file I used, could you please check it? I am using the same site as before.

https://49.gigafile.nu/1125-h8ed1dca360b842924cb9613c9e35502d

**Comment by luancarvalhomartins** [comment]
This last part was indeed a bug. I don't know if something changed in a matplotlib version, but anyway, fixed by https://github.com/luancarvalhomartins/PyAutoFEP/commit/0bcbd36b8cb38a9f08f432b371184473ca5f01e8

I am not closing the issue yet, as I didn't commit the code checking of dirs as mentioned in https://github.com/luancarvalhomartins/PyAutoFEP/issues/12#issuecomment-951208766

**Comment by baba-hashimoto** [comment]
Thanks for the reply. I updated the file, but I still get the same error. is there any other file I should change besides analyze_results.py? Also, I would like to have the same version of matplotlib, so please let me know which version you are using.

**Comment by luancarvalhomartins** [comment]
The matplotlib version I use in my test conda environment is:
```
matplotlib                3.4.2            py37h06a4308_0  
matplotlib-base           3.4.2            py37hab158f2_0  
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
```
I just tried with 
```
matplotlib                2.2.3            py37hb69df0a_0
```
and was able to reproduce your issue. I will _try_ to cook a code able to run using either versions 2 or 3, but if it proves complex, I guess I am just adding the requirement of a matplotlib version.

**Comment by luancarvalhomartins** [comment]
b6ed35491b6f66f0db58c332d230b60bb153945f fixes the issue when using the FEP run directory as input. The matplotlib version 2.2.3 issue is still present.
